### ISSUE TITLE
minio-java fails on gcs gateway

### ISSUE THREAD

**Issue by balamurugana** [minio/mint#198]
Below is an error
```
Running minio-java tests ... FAILED in 29 seconds
{ 
  "name": "minio-java",
  "function": "setBucketPolicy(String bucketName, String objectPrefix, PolicyType policyType)",
  "duration": 198,
  "status": "NA"
}
```

Respective error in the log
```
ErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=null, objectName=null, resource=/minio-java-test-3sktcip, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://10.99.185.131:9000/minio-java-test-3sktcip?policy=, headers=Content-Type: application/json
Host: 10.99.185.131:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 89241a7e86146de6270900e1bd782668c8c632b3b8b5e99b69de01d7f1e81b2f
x-amz-date: 20171021T164230Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171021/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-10-21T15-25-20Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14EFA37B6E362F33
Date: Sat, 21 Oct 2017 16:42:30 GMT
Transfer-Encoding: chunked
}

        at io.minio.MinioClient.execute(MinioClient.java:1200)
        at io.minio.MinioClient.executePut(MinioClient.java:1367)
        at io.minio.MinioClient.executePut(MinioClient.java:1389)
        at io.minio.MinioClient.setBucketPolicy(MinioClient.java:3870)
        at io.minio.MinioClient.setBucketPolicy(MinioClient.java:3901)
        at FunctionalTest.testSetBucketPolicy(FunctionalTest.java:2161)
        at FunctionalTest.setBucketPolicy_test4(FunctionalTest.java:2231)
        at FunctionalTest.runQuickTests(FunctionalTest.java:2531)
        at FunctionalTest.main(FunctionalTest.java:2573)
```

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio-java/pull/632
