### ISSUE TITLE
minio-py fails on gcs gateway

### ISSUE THREAD

**Issue by balamurugana** [minio/mint#200]
Below is an error
```
Running minio-py tests ... FAILED in 1 minutes and 13 seconds
{ 
  "function": "presigned_post_policy(post_policy)",
  "error": null,
  "description": "Tests presigned_post_policy api",
  "duration": 1.65,
  "args": {
    "post_policy": {
      "bucket_name": "ede64075-2314-4866-9f35-888523e208e3",
      "expires_in_days": 10,
      "prefix": "objectPrefix/"
    }
  },
  "name": "minio-py",
  "message": null,
  "alert": null,
  "status": "PASS"
}
```

Error from /mint/log/minio-py/error.log
```
Traceback (most recent call last):
  File "/mint/run/core/minio-py/tests.py", line 746, in test_get_bucket_policy
    policy_name = client.get_bucket_policy(bucket_name)
  File "/usr/local/lib/python3.5/dist-packages/minio/api.py", line 376, in get_bucket_policy
    raise ValueError("None Policy statement")
ValueError: None Policy statement

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mint/run/core/minio-py/tests.py", line 967, in <module>
    main()
  File "/mint/run/core/minio-py/tests.py", line 952, in main
    test_get_bucket_policy(client)
  File "/mint/run/core/minio-py/tests.py", line 754, in test_get_bucket_policy
    print_json(log_output)
  File "/mint/run/core/minio-py/tests.py", line 98, in print_json
    print(json.dumps(log_output))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: ValueError('None Policy statement',) is not JSON serializable
```

**Comment by nitisht** [comment]
Fixed by https://github.com/minio/minio-py/pull/587
