### ISSUE TITLE
minio-java tests fail for s3 gateway

### ISSUE THREAD

**Issue by nitisht** [minio/mint#226]
minio-java tests fail on S3 gateway

Server log:

```
ERRO[1138] Unable to fetch object info.                  cause=Prefix access is denied: minio-java-test-2h8e5r6/set-bucket-policy-read-write/minio-java-test-31k1f9d source=[gateway-handlers.go:84:gatewayAPIHandlers.GetObjectHandler()] stack=gateway-s3.go:411:(*s3Objects).GetObjectInfo gateway-handlers.go:78:(GatewayLayer).GetObjectInfo-fm gateway-handlers.go:82:gatewayAPIHandlers.GetObjectHandler gateway-router.go:91:(gatewayAPIHandlers).GetObjectHandler-fm
```

Mint log:

```json
(1/1) Running minio-java tests ... FAILED in 1 minutes and 17 seconds
{
  "name": "minio-java",
  "function": "setBucketPolicy(String bucketName, String objectPrefix, PolicyType policyType)",
  "duration": 5553,
  "status": "FAIL",
  "error": "error occured\nErrorResponse(code=AccessDenied, message=Access Denied., bucketName=null, objectName=null, resource=/minio-java-test-2h8e5r6/set-bucket-policy-read-write/minio-java-test-31k1f9d, requestId=3L137, hostId=3L137)\nrequest={method=GET, url=http://127.0.0.1:9000/minio-java-test-2h8e5r6/set-bucket-policy-read-write/minio-java-test-31k1f9d, headers=Host: 127.0.0.1:9000\nUser-Agent: Minio (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20171117T104550Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Type: application/xml\nServer: Minio/RELEASE.2017-11-17T01-22-21Z (linux; amd64)\nVary: Origin\nX-Amz-Request-Id: 14F7D9B03C6D6BD2\nDate: Fri, 17 Nov 2017 10:45:50 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1201), io.minio.MinioClient.executeGet(MinioClient.java:1294), io.minio.MinioClient.getObject(MinioClient.java:1594), io.minio.MinioClient.getObject(MinioClient.java:1506), FunctionalTest.testSetBucketPolicy(FunctionalTest.java:2291), FunctionalTest.setBucketPolicy_test4(FunctionalTest.java:2346), FunctionalTest.runQuickTests(FunctionalTest.java:2649), FunctionalTest.main(FunctionalTest.java:2691)]"
}
```

Error.log

```
root@mint-test:~# cat /tmp/mint-logs/minio-java/error.log 
error occured
ErrorResponse(code=AccessDenied, message=Access Denied., bucketName=null, objectName=null, resource=/minio-java-test-2h8e5r6/set-bucket-policy-read-write/minio-java-test-31k1f9d, requestId=3L137, hostId=3L137)
request={method=GET, url=http://127.0.0.1:9000/minio-java-test-2h8e5r6/set-bucket-policy-read-write/minio-java-test-31k1f9d, headers=Host: 127.0.0.1:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20171117T104550Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20171117/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=403, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-11-17T01-22-21Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: 14F7D9B03C6D6BD2
Date: Fri, 17 Nov 2017 10:45:50 GMT
Transfer-Encoding: chunked
}

        at io.minio.MinioClient.execute(MinioClient.java:1201)
        at io.minio.MinioClient.executeGet(MinioClient.java:1294)
        at io.minio.MinioClient.getObject(MinioClient.java:1594)
        at io.minio.MinioClient.getObject(MinioClient.java:1506)
        at FunctionalTest.testSetBucketPolicy(FunctionalTest.java:2291)
        at FunctionalTest.setBucketPolicy_test4(FunctionalTest.java:2346)
        at FunctionalTest.runQuickTests(FunctionalTest.java:2649)
        at FunctionalTest.main(FunctionalTest.java:2691)

```

**Comment by kannappanr** [comment]
This looks like a bug with AWS S3. A bug is being raised with AWS.

**Comment by nitisht** [comment]
Since its not Minio's issue, reducing the priority

**Comment by balamurugana** [comment]
It is minio gateway bug.  If anything is not supported, server should return `NotImplemented`, not `AccessDenied`

**Comment by kannappanr** [comment]
This issue has been raised in the AWS S3 forum. Here is the link to it. https://forums.aws.amazon.com/thread.jspa?threadID=267859

**Comment by kannappanr** [comment]
There is no activity on the forum thread

**Comment by nitisht** [comment]
closing as there is nothing much we can do from our side here.
