### ISSUE TITLE
At the time of running Mint with Minio Play server as test target, one of the 14 tests (s3)are failing always. 

### ISSUE THREAD

**Issue by sauravvats007** [minio/mint#374]
I am getting the following error at the time of running the podman command:
$  podman run -e "SERVER_ENDPOINT=10.9.75.33:9000" -e "DOMAIN=minio.com" -e "ACCESS_KEY=$$$$$$$$$" -e "SECRET_KEY=#######################" -e MINT_MODE=full minio/mint:latest

`(13/14) Running s3select tests ... FAILED in 1 seconds
Traceback (most recent call last):
  File "/mint/run/core/s3select/./tests.py", line 51, in main
    log_output = LogOutput(client.select_object_content,
  File "/mint/run/core/s3select/utils.py", line 57, in __init__
    self.__args_list = inspect.getargspec(meth).args[1:]
  File "/usr/lib/python3.10/inspect.py", line 1237, in getargspec
    raise ValueError("Function has keyword-only parameters or annotations"
ValueError: Function has keyword-only parameters or annotations, use inspect.signature() API which can support them

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mint/run/core/s3select/./tests.py", line 101, in <module>
    main()
  File "/mint/run/core/s3select/./tests.py", line 95, in main
    print(log_output.json_report(err))
UnboundLocalError: local variable 'log_output' referenced before assignment`

**Comment by moonkingcode520** [comment]
默认是 ENABLE_HTTPS=1 ，要求https, 你关闭这个  ENABLE_HTTPS=0 ，试试
